name = "auren-portfolio"
compatibility_date = "2025-04-30"
pages_build_output_dir = "dist"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "KV"
id = "80990b3f1ebd4c159e5d576398fc9bc1"